mod system;
mod data;
mod integrations;
mod functions;
//mod functions;

use uuid::Uuid;
use actix_cors::Cors;
use actix_web::http::header;
use std::env;
use std::io;
use std::path::Path;

use actix_web::{web, App, HttpResponse, HttpServer, Responder};
use actix_web::dev::{ServiceFactory, ServiceRequest, ServiceResponse};
use actix_web::body::BoxBody;
use std::sync::{Arc, Mutex, RwLock};
use rusqlite::{params, Connection, Result};
use data::db::sqlite::*;

use crate::data::models::{SystemData, SystemDataModel, SystemDataModelField, SystemFiles, SystemFileDirectory};
use crate::data::db::sqlite::repository_schema;
use crate::data::db::sqlite::repository_events;
use crate::data::db::sqlite::repository_files;

use crate::functions::models::SystemFunctions;
use crate::system::server::models::{SystemServer, SystemServerRoute};
use crate::integrations::models::{SystemIntegrations, SystemIntegrationModel};

use crate::system::logger;
use crate::system::models::AppState;
use crate::system::config_root::ConfigRoot;
use crate::system::keystore::{KeystoreManager, SecureStoreKeystoreProvider};
use crate::data::db::models::{DbColumn};

const SETUP_LOCK_FILENAME: &str = ".dxn-setup-lock.json";

/// Load `dxn-core/.env` (same directory as `config_path`) before reading `DXN_CORE_SECRET` etc.
/// Missing `.env` is OK (use shell env or systemd `EnvironmentFile`).
/// When `DXN_ENV=development` (default if unset), also loads `.env.development` with override.
fn load_dotenv_next_to_config(config_path: &str) {
    let dir = Path::new(config_path)
        .parent()
        .unwrap_or_else(|| Path::new("."));
    let dotenv_path = dir.join(".env");
    if dotenv_path.is_file() {
        if dotenvy::from_path(&dotenv_path).is_ok() {
            logger::log(&format!("Loaded environment from {}", dotenv_path.display()));
        }
    }
    let is_dev = env::var("DXN_ENV").unwrap_or_else(|_| "development".to_string()) == "development";
    if is_dev {
        let dev_env = dir.join(".env.development");
        if dev_env.is_file() {
            if dotenvy::from_path_override(&dev_env).is_ok() {
                logger::log(&format!(
                    "Loaded environment overrides from {}",
                    dev_env.display()
                ));
            }
        }
    }
}

fn ensure_provisioned_files(config_path: &str) -> io::Result<()> {
    let config = Path::new(config_path);
    if !config.is_file() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "config.json not found. This file must be generated by dxn-setup.",
        ));
    }

    let lock_path = config
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(SETUP_LOCK_FILENAME);
    if !lock_path.is_file() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "DXN core is not provisioned. Run dxn-setup before starting the server.",
        ));
    }

    Ok(())
}

async fn stats(data: web::Data<AppState>) -> impl Responder {
    let app_name = &data.app_name; // <- get app_name
    // Mutex example
    //let mut counter = data.counter.lock().unwrap();
    let mut counter = data.counter.write().unwrap();
    *counter += 1;

    let name = format!("Welcome to the {app_name} API, request number {counter}"); // <- response with app_name


    HttpResponse::Ok().body(name)
}

fn init_db(db_name: String, model: SystemDataModel) -> Result<()> {
    let mut columns: Vec<DbColumn> = Vec::new();
    
    // Filter for primary
    let primary: Option<SystemDataModelField> = model.fields
        .iter() // Get an iterator over references to items
        .filter(|item| item.primary == Some(true)) // Filter based on the Option<bool> field
        .cloned() // Clone the items to get owned copies in the new Vec
        .collect::<Vec<SystemDataModelField>>() // Collect the results into a new Vec<Item>
        .pop(); // Get last primary

    match primary {
        Some(primary_field) => {
            columns.push(repository::create_col_primary(primary_field.name, primary_field.datatype));
        },
        None => {
            // Insert id as primary key with TEXT type for UUID v7 support
            columns.push(repository::create_col_primary("id".to_string(), "TEXT".to_string()));
        }
    } 
    // Filter for primary
    let standard_fields: Vec<SystemDataModelField> = model.fields
        .iter() // Get an iterator over references to items
        .filter(|item| item.primary == Some(false) || item.primary == None) // Filter based on the Option<bool> field
        .cloned() // Clone the items to get owned copies in the new Vec
        .collect::<Vec<SystemDataModelField>>();

    
    for field in standard_fields {
        columns.push(repository::create_col(field.name, field.datatype, true));
    }
    /*
    columns.push(sqlite::create_col_primary(String::from("id"), String::from("integer")));
    columns.push(sqlite::create_col(String::from("name"), String::from("TEXT"), false));
    columns.push(sqlite::create_col(String::from("country"), String::from("TEXT"), true));
    */
    repository::create_dynamic_table(db_name.clone(), model.name, columns);
    Ok(())
}

/// Bootstraps data schemas using the hybrid approach:
/// 1. Initialize the schema table
/// 2. Sync config-defined schemas into the repository (source = "config")
/// 3. Load and initialize all schemas (config + runtime) from the repository
fn bootstrap_schemas(config_data: SystemData) -> Result<()> {
    // Step 1: Initialize the schema table
    repository_schema::init_schema_table()
        .map_err(|_e| rusqlite::Error::InvalidQuery)?;
    
    // Step 1b: Initialize the events table for event sourcing
    repository_events::init_events_table()
        .map_err(|_e| rusqlite::Error::InvalidQuery)?;
    
    // Step 2: Sync config-defined schemas into the repository
    if let Some(schemas) = config_data.public {
        for mut schema in schemas {
            // Config schemas default to db="public" if not specified
            if schema.db.is_empty() {
                schema.db = "public".to_string();
            }
            
            // Upsert into repository with source="config"
            if let Err(e) = repository_schema::upsert_schema(&schema, "config") {
                eprintln!("Failed to register config schema '{}': {}", schema.name, e);
            }
        }
    }
    
    // Handle private schemas from config
    if let Some(schemas) = config_data.private {
        for mut schema in schemas {
            if schema.db.is_empty() {
                schema.db = "private".to_string();
            }
            
            if let Err(e) = repository_schema::upsert_schema(&schema, "config") {
                eprintln!("Failed to register config schema '{}': {}", schema.name, e);
            }
        }
    }
    
    // Step 3: Load all schemas from repository and create their database tables
    match repository_schema::get_all_schemas() {
        Ok(all_schemas) => {
            for schema in all_schemas {
                let db_name = if schema.db.is_empty() { "public".to_string() } else { schema.db.clone() };
                if let Err(e) = init_db(db_name, schema.clone()) {
                    eprintln!("Failed to init table for schema '{}': {}", schema.name, e);
                }
            }
        }
        Err(e) => {
            eprintln!("Failed to load schemas from repository: {}", e);
        }
    }
    
    Ok(())
}

/// Bootstraps file directories from config
/// 
/// 1. Initialize the file_directories table
/// 2. Sync config-defined directories into the repository (source = "config")
/// 3. Create filesystem dirs under project_root so uploads stay in project
fn bootstrap_files(config_files: Option<SystemFiles>, project_root: &str) -> Result<()> {
    // Step 1: Initialize the file_directories table
    repository_files::init_files_table()
        .map_err(|_e| rusqlite::Error::InvalidQuery)?;
    
    // Step 2: Sync config-defined directories into the repository
    if let Some(files_config) = config_files {
        if let Some(directories) = files_config.directories {
            for directory in directories {
                // Upsert into repository with source="config"
                if let Err(e) = repository_files::upsert_directory(&directory, "config") {
                    eprintln!("Failed to register config file directory '{}': {}", directory.name, e);
                } else {
                    // Ensure the directory exists on the filesystem under project root
                    if directory.provider == "local" {
                        let base_path = format!("{}/dxn-files{}", project_root, directory.path);
                        if let Err(e) = std::fs::create_dir_all(&base_path) {
                            eprintln!("Warning: Failed to create directory '{}': {}", base_path, e);
                        }
                    }
                }
            }
        }
    }
    
    Ok(())
}

/// Legacy function - kept for reference but replaced by bootstrap_models
#[allow(dead_code)]
fn create_database(data: SystemData) -> Result<()> {
    match data.public {
        Some(vec) => {
            // 'vec' is a Vec<SystemDataModel> here
            if vec.is_empty() {
                //println!("Vector is present but empty.");
            } 
            else {
                //println!("Setup API for object: {:?}", vec);
                for element in vec {
                    //println!("Setup DB for object: {:?}", element.name);
                    let _ = init_db("public".to_string(), element);
                }
            }
        }
        None => {
            // println!("No vector present.");
        }
    }
    Ok(())
}

fn create_functions(functions: SystemFunctions)  -> Result<()> {
    match functions.public {
        Some(vec) => {
            // 'vec' is a Vec<SystemDataModel> here
            if vec.is_empty() {
                //println!("Vector is present but empty.");
            } 
            else {
            //crate::functions::manager::
                crate::functions::manager::init(vec.clone());
                //crate::functions::runner::run(vec);
            }
        }
        None => {
            // println!("No vector present.");
        }
    }
    Ok(())
}

fn init_integration(integration_name: String, model: SystemIntegrationModel) -> Result<()> {
    crate::integrations::manager::init(model);
    Ok(())
}

fn create_integrations(data: SystemIntegrations) -> Result<()> {
    match data.public {
        Some(vec) => {
            // 'vec' is a Vec<SystemDataModel> here
            if vec.is_empty() {
                //println!("Vector is present but empty.");
            } 
            else {
                //println!("Setup API for object: {:?}", vec);
                for element in vec {
                    //println!("Setup DB for object: {:?}", element.name);
                    let _ = init_integration("public".to_string(), element);
                }
            }
        }
        None => {
            // println!("No vector present.");
        }
    }
    Ok(())
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {

    // DATA — resolve config path first so `.env` loads from the same directory (dxn-core root).
    let file_path = "./config.json".to_string();
    load_dotenv_next_to_config(&file_path);

    logger::log("App initialized");
    ensure_provisioned_files(&file_path)?;

    let raw = std::fs::read_to_string(&file_path)?;
    let config_root: ConfigRoot = serde_json::from_str(&raw).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("invalid config.json: {}", e),
        )
    })?;

    let lock_path = system::setup_lock::setup_lock_path_for_config(&file_path);
    let setup_lock = system::setup_lock::load_setup_lock(&lock_path).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!(".dxn-setup-lock.json: {}", e),
        )
    })?;

    system::config_root::cross_check_vault_with_lock(&setup_lock, config_root.vault.as_ref())
        .map_err(|msg| io::Error::new(io::ErrorKind::InvalidData, msg))?;

    let secret = env::var("DXN_CORE_SECRET").map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "DXN_CORE_SECRET is not set. Add it to dxn-core/.env (same folder as config.json) or export it in the environment.",
        )
    })?;

    system::vault_verify::verify_vault_fingerprint(
        &secret,
        &setup_lock.keystore.kdf,
        &setup_lock.keystore.key_fingerprint,
    )
    .map_err(|e| {
        io::Error::new(
            io::ErrorKind::PermissionDenied,
            format!("Vault verification failed: {}", e),
        )
    })?;

    let project_root = system::files::project_root::resolve_project_root_with_config(&file_path)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;
    let auth_root = system::files::project_root::resolve_auth_root_with_config(&file_path, &project_root)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;
    let dxn_files_root = system::files::project_root::dxn_files_root(&project_root);
    if !std::path::Path::new(&dxn_files_root).is_dir() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("DXN files root not found: {}", dxn_files_root),
        ));
    }
    logger::log(format!("Resolved project_root: {}", project_root).as_str());
    logger::log(format!("Resolved dxn_files_root: {}", dxn_files_root).as_str());
    logger::log(format!("Resolved auth_root: {}", auth_root).as_str());
    system::files::manager::set_project_root(&project_root);

    let (vault_rel, key_rel) =
        system::config_root::keystore_paths(&setup_lock, &config_root);
    let vault_abs =
        system::files::project_root::resolve_under_project_root(&project_root, vault_rel);
    let key_abs = system::files::project_root::resolve_under_project_root(&project_root, key_rel);

    let config_checksum = system::core_state::compute_config_checksum(&file_path)?;
    let state_path = system::core_state::core_state_path(&file_path);
    let state_opt = system::core_state::load_optional(&state_path)?;

    if let Some(ref s) = state_opt {
        if s.initialized && s.instance_id != setup_lock.instance_id {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "instance_id in .dxn-core-state.json does not match .dxn-setup-lock.json; remove stale state or use the correct project.",
            ));
        }
        if s.initialized && s.config_checksum != config_checksum {
            if env::var("DXN_ALLOW_CONFIG_CHECKSUM_DRIFT").unwrap_or_default() == "1" {
                logger::log(
                    "WARNING: config.json checksum drift vs .dxn-core-state.json; continuing (DXN_ALLOW_CONFIG_CHECKSUM_DRIFT=1). State checksum will be updated.",
                );
            } else {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "config.json changed since last successful run (checksum drift vs .dxn-core-state.json). Re-run dxn-setup, restore the previous config, delete .dxn-core-state.json if intentional, or set DXN_ALLOW_CONFIG_CHECKSUM_DRIFT=1 after review.",
                ));
            }
        }
    }

    let seed_path =
        system::config_root::resolve_keystore_seed_path(&setup_lock, &config_root, &file_path);
    let had_staging = seed_path
        .as_ref()
        .map(|p| system::keystore_ingest::staging_ready(p))
        .unwrap_or(false);

    let keystore = if had_staging {
        let seed_dir = seed_path.as_ref().expect("had_staging implies path");
        let prov = system::keystore_ingest::ingest_staged_secrets(seed_dir, &vault_abs, &key_abs)
            .map_err(|e| {
                io::Error::new(
                    io::ErrorKind::Other,
                    format!("Keystore seed ingest failed (staging dir not removed): {}", e),
                )
            })?;
        logger::log("Keystore seed ingest completed; staging directory removed.");
        Some(KeystoreManager::new(
            Arc::new(prov) as Arc<dyn crate::system::keystore::KeystoreProvider>,
        ))
    } else if vault_abs.is_file() && key_abs.is_file() {
        let prov = SecureStoreKeystoreProvider::open(&vault_abs, &key_abs).map_err(|e| {
            io::Error::new(
                io::ErrorKind::Other,
                format!("Failed to open SecureStore keystore: {}", e),
            )
        })?;
        logger::log("Keystore opened (SecureStore).");
        Some(KeystoreManager::new(
            Arc::new(prov) as Arc<dyn crate::system::keystore::KeystoreProvider>,
        ))
    } else {
        logger::log(
            "Keystore vault/key files not found and no staging directory to ingest; continuing without keystore.",
        );
        None
    };

    let new_state = match state_opt {
        None => system::core_state::CoreState::new_first_write(
            setup_lock.instance_id.clone(),
            config_checksum.clone(),
            true,
        ),
        Some(mut s) => {
            if !s.initialized {
                s.config_checksum = config_checksum.clone();
            } else if env::var("DXN_ALLOW_CONFIG_CHECKSUM_DRIFT").unwrap_or_default() == "1"
                && s.config_checksum != config_checksum
            {
                s.config_checksum = config_checksum.clone();
            }
            s.updated_at = Some(chrono::Utc::now());
            s.initialized = true;
            s.instance_id = setup_lock.instance_id.clone();
            s.keystore_seed_ingested = true;
            s.format_version = 1;
            s.migration_version = s.migration_version.max(1);
            s
        }
    };
    system::core_state::save(&state_path, &new_state)?;

    let system_data = config_root.system;

    let sa_identity = system::auth::sa_identity::load_sa_identity(&auth_root).ok();
    if sa_identity.is_none() {
        logger::log("SA identity file not found; auth and guarded routes will return 503/401 until .sa-identity.json is provisioned.");
    }
    let app = web::Data::new(AppState {
        app_name: String::from("dxnet"),
        counter: RwLock::new(0),
        db_name: String::from("person"),
        system: system_data,
        uuid: Uuid::now_v7(),
        project_root,
        dxn_files_root,
        sa_identity,
        keystore,
    });


    /// DB
    // Note: config.json is now loaded above and used for system initialization
 
    // Bootstrap schemas (hybrid approach: config + runtime schemas)
    println!("Init -> Schema Repository");
    bootstrap_schemas(app.system.data.clone()); 
    
    // Bootstrap file directories (hybrid approach: config + runtime directories)
    println!("Init -> File Directories");
    bootstrap_files(app.system.files.clone(), &app.project_root);
    
    println!("Init -> Integrations");
    crate::integrations::manager::set_project_root(&app.project_root);
    create_integrations(app.system.integrations.clone()); 

    println!("Init -> Functions");
    create_functions(app.system.functions.clone());

    println!("Init -> Server");
 
    // Determine environment: default to "development" if DXN_ENV is not set
    let env = env::var("DXN_ENV").unwrap_or_else(|_| "development".to_string());
    let is_dev = env == "development";

    HttpServer::new(move || {
        // Configure CORS based on environment
        let cors = if is_dev {
            // In development, allow any origin for easier local testing (web, simulator, devices)
            Cors::default()
                .allow_any_origin()
                .allowed_methods(vec!["GET", "POST", "PUT", "DELETE", "OPTIONS"])
                .allowed_headers(vec![header::AUTHORIZATION, header::ACCEPT, header::CONTENT_TYPE])
                .max_age(3600)
        } else {
            // In non-development environments, restrict origins explicitly.
            // Adjust allowed origins as needed for your deployment.
            Cors::default()
                .allowed_methods(vec!["GET", "POST", "PUT", "DELETE", "OPTIONS"])
                .allowed_headers(vec![header::AUTHORIZATION, header::ACCEPT, header::CONTENT_TYPE])
                .supports_credentials()
                .max_age(3600)
        };

        App::new()
            .wrap(cors)
            // Configure app state
            .app_data(app.clone())
            // Auth: login only (no guard)
            .service(web::scope("/api/auth").configure(system::auth::controller::config))
            // Guarded API and dashboard: require Authorization: Bearer <token>
            .service(
                web::scope("/api/data")
                    .wrap(actix_web::middleware::from_fn(system::auth::middleware::sa_auth_middleware))
                    .configure(system::server::http::controllers::data::config),
            )
            .service(
                web::scope("/api/function")
                    .wrap(actix_web::middleware::from_fn(system::auth::middleware::sa_auth_middleware))
                    .configure(|cfg| { system::server::http::controllers::function::config(cfg, app.system.functions.clone())}),
            )
            .service(
                web::scope("/api/config")
                    .wrap(actix_web::middleware::from_fn(system::auth::middleware::sa_auth_middleware))
                    .configure(|cfg| { system::server::http::controllers::config::config(cfg)}),
            )
            .service(
                web::scope("/api/schema")
                    .wrap(actix_web::middleware::from_fn(system::auth::middleware::sa_auth_middleware))
                    .configure(|cfg| { system::server::http::controllers::schema::config(cfg)}),
            )
            .service(
                web::scope("/api/events")
                    .wrap(actix_web::middleware::from_fn(system::auth::middleware::sa_auth_middleware))
                    .configure(system::server::http::controllers::events::config),
            )
            .service(
                web::scope("/api/files")
                    .wrap(actix_web::middleware::from_fn(system::auth::middleware::sa_auth_middleware))
                    .configure(system::server::http::controllers::files::config),
            )
            .service(
                web::scope("/server")
                    .wrap(actix_web::middleware::from_fn(system::auth::middleware::sa_auth_middleware))
                    .configure(|cfg| system::server::http::controllers::server::config(cfg, app.system.server.clone())),
            )
            
            
            // Add default route
            .route("/_.stats", web::get().to(stats))
            .route("/", web::get().to(DXN))
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
 

}





/*
     Server::build()
    .configure( |cfg : &mut ServiceConfig| {
        cfg.bind( "site1", "0.0.0.0:8000").expect("bind failed");
        cfg.bind( "site2", "0.0.0.0:9000").expect("bind failed");
        cfg.apply(callback).expect("Failed to configure HTTP service");
        Ok(())
    }).expect("Unable to configure")
    .run().expect("Failed to start HTTP server");
    
fn callback(runtime : &mut ServiceRuntime)  {
    runtime.service("site1",
        HttpService::build()
            .finish(
                App::new()
                    .wrap(middleware::DefaultHeaders::new().header(http::header::CACHE_CONTROL, "no-cache"))
                    //.wrap(middleware::Compress::default())  // <-- enabling this would prevent chunked response.
                    .wrap(middleware::Logger::default())
                    .service(
                        web::resource("/iot/events")
                            .route(web::get().to(outbound))
                            .route(web::put().to_async(inbound))
                    )
            ) 
    );

    runtime.service("site2",
        HttpService::build()
            .finish(
                App::new()
                    .service(
                        web::resource("/")
                            .route(web::get().to(|| HttpResponse::Ok()))
                    )
            ) 
    );
}
 */
async fn DXN(data: web::Data<AppState>) -> impl Responder {
    let html_content = r#"
        <!DOCTYPE html>
        <html>
        <head>
            <title>DXN</title>
        </head>
        <body>
        </body>
        </html>
    "#;
    HttpResponse::Ok().content_type("text/html").body(html_content)
}
